server:
    name: car_talk
    port: 6789
    host: 0.0.0.0
    env: dev
    version: 1.0.0
    log_level: INFO


database:
  host: localhost
  port: 5432
  user: root
  password: 123456
  name: car_talk
  charset: utf8mb4


redis:
  host: localhost
  port: 6379
  password: aFzqEWAEwPT2mc2N2fk9mZ69KRx0jEV_4krUgKTUfKV8bXZzaCveY24WyE2FaRdW


mcp:
  server_ip: 10.67.37.11
